import { Inter } from "next/font/google";
import "./globals.css";
import Image from "next/image";
import { ClerkProvider, UserButton, auth } from "@clerk/nextjs";
import { sql } from "@vercel/postgres";
import CreateProfile from "@/components/CreateProfile";
import CreatePost from "@/components/CreatePost";
import Post from "@/components/Post";
import connect from "@/../public/connect.png";
import HaveFun from "@/../public/HaveFun.png";
import Tim from "@/../public/tim.png";
import Millie from "@/../public/millie.jpg";
import John from "@/../public/john.jpg";
import Mary from "@/../public/mary.png";
import Charlie from "@/../public/charlie.png";
import Chris from "@/../public/chris.png";
import Nicola from "@/../public/nicola.jpg";
//import Laura from "@/components/users/Laura"; <Laura />

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({ children }) {
  const { userId } = auth();

  // go and get the user profile from our db
  const profileRes =
    await sql`SELECT * FROM profile WHERE clerk_user_id = ${userId}`;
  console.log(profileRes);

  return (
    <ClerkProvider>
      <html lang="en">
        <body className={inter.className}>
          <UserButton afterSignOutUrl="/" />
          <div classname="allpost">
            <Image
              src={connect}
              alt="connecting people"
              width="100"
              height="100"
              className="connect"
            />

            <div class="container">
              <Image
                src={HaveFun}
                alt="Have fun"
                width="40"
                height="55"
                className="Fun"
                title="Laura"
              />

              <Image
                src={Tim}
                alt="Timing Intelligent Magic"
                width="35"
                height="52"
                className="Fun"
                title="Tim"
              />
              <Image
                src={Millie}
                alt="Have fun"
                width="35"
                height="52"
                className="Fun"
                title="Millie"
              />
              <Image
                src={John}
                alt="Have fun"
                width="35"
                height="52"
                className="Fun"
                title="John"
              />
              <Image
                src={Mary}
                alt="Have fun"
                width="35"
                height="52"
                className="Fun"
                title="Mary"
              />
              <Image
                src={Charlie}
                alt="Have fun"
                width="35"
                height="52"
                className="Fun"
                title="Charlie"
              />
              <Image
                src={Chris}
                alt="Have fun"
                width="45"
                height="50"
                className="Fun"
                title="Chris"
              />
              <Image
                src={Nicola}
                alt="Have fun"
                width="35"
                height="52"
                className="Fun"
                title="Nicola"
              />
            </div>

            <Post />
          </div>

          {/* if the user has a profile, carry on as normal */}
          {profileRes.rowCount !== 0 && children}

          {/* if the user DOESN'T has a profile, show the CreateProfile component */}
          {profileRes.rowCount === 0 && <CreateProfile />}

          <h2>Would you like to create a Post</h2>
          <CreatePost />
        </body>
      </html>
    </ClerkProvider>
  );
}
